name: CI

on:
  push:
    # branches:
    #   - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
      # setup pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install pnpm dependencies (with cache)
        uses: covbot/pnpm-install-with-cache@v1
      - run: pnpm buildall
      - run: pnpm genall
      - run: pnpm test
      # - name: Bump version
      #   if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/fields-selection'
      #   uses: remorses/bump-version@js
      #   with:
      #     version_file: VERSION
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - run: yarn buildall
      # - name: Publish
      #   run: |
      #     cd genql-cli && npm publish --verbose --access public --tag beta
      #     cd ../genql-runtime && npm publish --verbose --access public --tag beta
      #   if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/fields-selection'
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
